# Generated by Django 5.1 on 2024-08-23 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_item_drop_from'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='drop_from',
        ),
    ]
