# Generated by Django 5.1 on 2024-08-23 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
        ('monsters', '0002_alter_dropitem_monster'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='drop_item',
            field=models.ManyToManyField(to='items.item'),
        ),
    ]
