# Generated by Django 5.1 on 2024-08-23 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0003_monster_drop_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DropItem',
        ),
    ]
