# Generated by Django 5.1 on 2024-08-23 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_remove_item_drop_from'),
        ('monsters', '0004_delete_dropitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monster',
            name='drop_item',
        ),
        migrations.AddField(
            model_name='monster',
            name='drop_item',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='items.item'),
        ),
    ]
